<div class="col-md-12">
    <h2><i class="fa fa-table"></i> Listagem </h2>
</div>
</div>
<!-- /. ROW  -->
<hr />

<div class="row col-md-12">
    
    <table class="table table-bordered table-head table-striped">
        <caption><i class="fa fa-filter"></i> 10 Processos mais recentes</caption>
        <thead>
        <tr>
            <th><i class="fa fa-file"></i> Nome</th>
            <th><i class="fa fa-calendar"></i> Data</th>
            <th><i class="fa fa-folder-open-o"></i> Detalhes</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($this->records as $record): ?>
                <tr>
                    <td><?= $this->escape($record['nome']) ?></td>
                    <td><?= $this->escape($record['dia']) ?></td>
                    <td><a href="/dashboard/view/<?= $this->escape($record['id']);?>" class="btn btn-info btn-xs"><i class="fa fa-eye"></i></a> </td>
                </tr>
        
            <?php endforeach;?>
        
        </tbody>
    </table>
    
    
    
</div>