<div class="col-md-12">
	<h2><i class="fa fa-globe"></i> Definições API </h2>
</div>
</div>
<!-- /. ROW  -->
<hr />

<div class="row col-md-12">

<h3><i class="fa fa-exchange"></i> Métodos para comunicação com SIGA</h3>

	<ul>
		<li>
			<i class="fa fa-code">Token segurança: Nt8w6nMhF1E9MILX5SrWuQo893rlp7eZ</i>
		</li>
	</ul>


<h4 style="padding-top: 15px;"><i class="fa fa-code-fork"></i> Métodos::Definições</h4>

	<ul>
		<li><i class="fa fa-cloud-upload"></i> Procurar por data: <code>//server/%%TOKEN%%/date/%%inserir a data pretendida (Formato ISO 8601: 2000-01-31)%%</code></li>

		<li><i class="fa fa-cloud-upload"></i> Procurar por processo: <code>//server/%%TOKEN%%/processo/%%inserir o nome do processo%%</code></li>
	</ul>


</div>