<div class="col-md-12">
	<h2><i class="fa fa-globe"></i> Definições API </h2>
</div>
</div>
<!-- /. ROW  -->
<hr />

<div class="row col-md-12">

<h3><i class="fa fa-exchange"></i> Métodos para comunicação com SIGA</h3>

	<ul>
		<li>
			<i class="fa fa-code">Token segurança: <code><?=$this->token[0]['token']?></code></i>
		</li>
		<li> Erro de Token: <a href="/api/rest/token/Nt8wfgMJ6nMhF1E9MILXss5SrWuQo893rlp7eZ/date/2016-05-27" class="btn btn-danger btn-xs"><i class="fa fa-link"></i></a></li>
	</ul>


<h4 style="padding-top: 15px;"><i class="fa fa-code-fork"></i> Métodos::Definições POST</h4>

	<ul>
		<li><i class="fa fa-cloud-upload"></i> Procurar por data: <code>//server/api/rest/token/%%TOKEN%%/date/%%inserir a data pretendida (Formato ISO 8601: 2000-01-31)%%</code></li>
		<li>Exemplo: <b>OK</b> <a href="/api/rest/token/Nt8w6nMhF1E9MILX5SrWuQo893rlp7eZ/date/2016-05-27" class="btn btn-success btn-xs"><i class="fa fa-link"></i></a></li>
		<li>Exemplo: <b>Não OK</b> <a href="/api/rest/token/Nt8w6nMhF1E9MILX5SrWuQo893rlp7eZ/datinha/2016-05-27" class="btn btn-danger btn-xs"><i class="fa fa-link"></i></a></li>

		<li><i class="fa fa-cloud-upload"></i> Procurar por processo: <code>//server/api/rest/token/%%TOKEN%%/processo/%%inserir o nome do processo%%</code></li>
		<li>Exemplo: <b>OK</b> <a href="/api/rest/token/Nt8w6nMhF1E9MILX5SrWuQo893rlp7eZ/processo/processo1" class="btn btn-success btn-xs"><i class="fa fa-link"></i></a></li>
		<li>Exemplo: <b>Não OK</b> <a href="/api/rest/token/Nt8w6nMhF1E9MILX5SrWuQo893rlp7eZ/processso/processo1" class="btn btn-danger btn-xs"><i class="fa fa-link"></i></a></li>
	</ul>




<h4 style="padding-top: 15px;"><i class="fa fa-code-fork"></i> Métodos::Definições GET</h4>

<ul>
	<li><i class="fa fa-cloud-upload"></i> Procurar por processo: <code>URL a definir pela API SIGA</code></li>
	<li>Este método é depois incluido na página dos detalhes do Processo</li>
</ul>


</div>