<div class="col-md-12">
	<h2><i class="fa fa-cogs"></i> Definições </h2>
</div>
</div>
<!-- /. ROW  -->
<hr />
<div class="row col-md-12">
	<h3><i class="fa fa-users"></i> Utilizadores </h3>
	<hr />
</div>
<div class="row col-md-6">

	<?php if (count($this->messages) > 0): ?>
		<div class="alert alert-success alert-dismissable" style="margin-top: 10px">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
			<i class="fa fa-check-square"></i> <?=$this->messages[0];?>
		</div>
	<?php endif; ?>


	<table class="table table-bordered table-striped table-head">
		<caption>

			<span class="pull-right"><a href="/admin/newuser" class="btn btn-primary"><i class="fa fa-plus"></i> Adicionar</a></span>
		</caption>
		<thead>
			<tr>
				<th>Nome</th>
				<th>Palavar Passe</th>
				<th>Administrador</th>
				<th>Edição</th>
			</tr>

		</thead>
		<tbody>
			<?php foreach ($this->users as $user): ?>
				<tr>
					<td><?=$user["username"];?></td>
					<td><?=$user["password"];?></td>
					<td><?=$user["admin"] ? "Sim" : "Não";?></td>
					<td>
						<a href="/admin/userdel/<?=$user['id'];?>" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></a>
						<a href="/admin/useredit/<?=$user['id'];?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i></a>
					</td>
				</tr>

			<?php endforeach;?>
		</tbody>

	</table>
</div>
	<div class="row col-md-12">
		<h3><i class="fa fa-folder-open"></i> Endereços </h3>
		<hr />
	</div>

<div class="row">
	<div class="col-lg-8">
		<i class="fa fa-server"></i> Polycom
		<div class="input-group input-group-md">

			<label class="sr-only" for="polycom">Polycom</label>
			<input type="text" name="polycom" class="form-control input-md" id="polycom" placeholder="Localização">
      <span class="input-group-btn">
        <button class="btn btn-primary btn-md" type="submit"><i class="fa fa-chain"></i> Alterar</button>
      </span>
		</div>
	</div>
</div>


<div class="row" style="padding-top: 8px;">
	<div class="col-lg-8">
		<i class="fa fa-server"></i> SAN
		<div class="input-group input-group-md">

			<label class="sr-only" for="san">SAN</label>
			<input type="text" name="san" class="form-control input-md" id="san" placeholder="Localização">
      <span class="input-group-btn">
        <button class="btn btn-primary btn-md" type="submit"><i class="fa fa-chain"></i> Alterar</button>
      </span>
		</div>
	</div>
</div>

<div class="row" style="padding-top: 8px;">
	<div class="col-lg-8">
		<i class="fa fa-server"></i> SIGA
		<div class="input-group input-group-md">

			<label class="sr-only" for="siga">SIGA</label>
			<input type="text" name="siga" class="form-control input-md" id="san" placeholder="Localização">
      <span class="input-group-btn">
        <button class="btn btn-primary btn-md" type="submit"><i class="fa fa-chain"></i> Alterar</button>
      </span>
		</div>
	</div>
</div>