<div class="col-md-12">
	<h2>Definições </h2>
</div>
</div>
<!-- /. ROW  -->
<hr />

<div class="row col-md-6">


	<table class="table table-bordered table-striped">
		<caption>
			<i class="fa fa-users"></i> Utilizadores
			<span class="pull-right"><a href="/admin/newuser" class="btn btn-primary"><i class="fa fa-plus"></i> Adicionar</a></span>
		</caption>
		<thead>
			<tr>
				<th>Nome</th>
				<th>Palavar Passe</th>
				<th>Administrador</th>
			</tr>

		</thead>
		<tbody>
			<?php foreach ($this->users as $user): ?>
				<tr>
					<td><?=$user["username"];?></td>
					<td><?=$user["password"];?></td>
					<td><?=$user["admin"] ? "Sim" : "Não";?></td>
				</tr>

			<?php endforeach;?>
		</tbody>



	</table>



</div>